"""Shared MVP contract constants for schema, warnings, and gates."""

SCHEMA_VERSION = "0.1.0"
SUPPORTED_AUDIO_EXTENSIONS = {".wav", ".mp3", ".flac", ".m4a"}
MIN_DURATION_SECONDS = 30.0
MAX_DURATION_SECONDS = 90.0
SUPPORTED_FRET_RANGE = {"min": 0, "max": 20}
STANDARD_TUNING = ["E2", "A2", "D3", "G3", "B3", "E4"]
CONFIDENCE_THRESHOLDS = {
    "notes": 0.55,
    "chords": 0.60,
    "sections": 0.50,
    "fingering": 0.65,
}
WARNING_LOW_NOTE_CONFIDENCE = "LOW_NOTE_CONFIDENCE"
WARNING_LOW_CHORD_CONFIDENCE = "LOW_CHORD_CONFIDENCE"
WARNING_LOW_SECTION_CONFIDENCE = "LOW_SECTION_CONFIDENCE"
WARNING_LOW_FINGERING_CONFIDENCE = "LOW_FINGERING_CONFIDENCE"
WARNING_UNPLAYABLE_NOTE = "UNPLAYABLE_NOTE"
WARNING_URL_POLICY_GATE = "URL_POLICY_GATE"
WARNING_DEGRADED_CHORD_ONLY = "DEGRADED_CHORD_ONLY"
HARD_FAIL_UNPLAYABLE_TAB = "UNPLAYABLE_TAB"
HARD_FAIL_LOW_CONFIDENCE_WITHOUT_WARNING = "LOW_CONFIDENCE_WITHOUT_WARNING"
HARD_FAIL_MISSING_GOLDEN_FIXTURE_RECORD = "MISSING_GOLDEN_FIXTURE_RECORD"

HARD_FAIL_RAW_MIDI_ONLY = "RAW_MIDI_ONLY"
